### ISSUE TITLE
Integration broken for Redis

### ISSUE THREAD

**Issue by gegnew** [taskiq-python/taskiq-fastapi#11]
I've set this up as described in the docs, except for putting `broker.startup` and `broker.shutdown` in the FastAPI lifespan function rather than in the `startup` and `shutdown` decorated functions.

It works fine with `InMemoryBroker`: I start FastAPI, then `kiq` a task either from a separate script or somewhere in my app (like a FastAPI router) and receive a result. When I use `ListQueueBroker`, I get nothing. However, if I run the `ListQueueBroker` without the FastAPI integration, as it's own script, it works fine.

Additionally, I get a warning if I use the `result_backend` arg for the `ListQueueBroker`, so instead I use `.with_result_backend`, as the warning indicates (see below).

```python
# broker.py
from taskiq import InMemoryBroker
import asyncio
from taskiq_redis import RedisAsyncResultBackend, ListQueueBroker
import taskiq_fastapi

url = "redis://127.0.0.1:6379"

redis_async_result = RedisAsyncResultBackend(redis_url=url)
broker = ListQueueBroker(
    url=url
    # result_backend=redis_async_result,
).with_result_backend(redis_async_result)

taskiq_fastapi.init(broker, "app.main:app")


@broker.task
async def add_one(value: int) -> int:
    return value + 1

async def main():
    await broker.startup()
    task = await add_one.kiq(1)
    result = await task.wait_result(timeout=2)
    print(f"Task execution took: {result.execution_time} seconds.")
    if not result.is_err:
        print(f"Returned value: {result.return_value}")
    else:
        print("Error found while executing task.")
    await broker.shutdown()


if __name__ == "__main__":
    asyncio.run(main())
```

```python
# app.py
@asynccontextmanager
async def lifespan(app: FastAPI):
    if not broker.is_worker_process:
        print("Starting broker")
        await broker.startup()

    yield

    if not broker.is_worker_process:
        print("Stopping broker")
        await broker.shutdown()

app = FastAPI(
    debug=settings.DEBUG,
    lifespan=lifespan,
)
```

and then `uvicorn app.main:app` or however you like starting FastAPI

**Comment by gegnew** [comment]
so this works:
```sh
> taskiq broker:broker
> python broker.py
```

and this doesn't:
```sh
> uvicorn 'app.main:app'
> python broker.py
```

**Comment by s3rius** [comment]
Hi and thanks for your interest in this project. Your code listing works as expected. I guess you just a bit mislead by the documentation. The `main` function in your `broker.py` file just starts up the broker and sends a task. Nothing more. 

The FastAPI integration executes all startup and shutdown events of your application during startup and shutdown of your workers. This is helpful, because it allows you to use the same dependencies as in your handlers in taskiq tasks and also, it automatically resolves all tasks used in your application, so you don't have to import them manually. 

To verify that everything is working, let's create the endpoint where we call the task you've defined.

```python
@app.get("/")
async def index():
    task = await add_one.kiq(1)
    result = await task.wait_result(timeout=2)
    return {"res": result.return_value, "time": result.execution_time, "is_err": result.is_err}
```
Then you need to start both application and workers.

```python
uvicorn 'app.main:app'
taskiq broker:broker
```

After that, if you send `GET /` request to your application, the task is going to be sent to workers. 

I hope that it helped you to gain more understanding of how to use the project. If you have any ideas how we can improve the documentation, please tell us. We want our library to be as easy to use and accessible as possible.

**Comment by s3rius** [comment]
So, all tasks are executed on workers to offload the CPU of your application. That's why, when you call  `uvicorn app` it won't be able to handle tasks. It's intentional. 

But, if you really want to spin up actual task listeners along with your application, we got you covered. You can read more about such setups here: https://taskiq-python.github.io/guide/dynamic-brokers.html

But I would try to avoid this, because it introduces more load on CPU and network for each application's instance, and it loses cool feature of self-healing that workers can do if something will go wrong with network or redis connectivity.

**Comment by gegnew** [comment]
🤦  thanks!
